/// This file is generated by `BaseASTVisitor.tt`. Please do not edit directly as it will be overwritten.

namespace RadParser.AST.Node;

/// <summary>
/// An interface for a visitor that can visit all nodes in the AST. This interface is generated through a T4 template so
/// that it can be kept up to date with the AST nodes without having to manually update it every time a new node is added.
/// </summary>
public interface IBaseASTVisitor {
  void Visit(BinaryOperation node);

  void Visit(DeclaratorKeyword node);

  void Visit(EmptyExpression node);

  void Visit(FunctionCallExpression node);

  void Visit(FunctionDeclaration node);

  void Visit(FunctionScope node);

  void Visit(FunctionScopeStatement node);

  void Visit(LiteralExpression node);

  void Visit(Modifier node);

  void Visit(Module node);

  void Visit(NamedTypeParameter node);

  void Visit(NumericLiteral node);

  void Visit(OperationalKeyword node);

  void Visit(Operator node);

  void Visit(PositionalParameter node);

  void Visit(PrimitiveTypeReference node);

  void Visit(Reference node);

  void Visit(ReferenceExpression node);

  void Visit(Statement node);

  void Visit(Token node);

  void Visit(TopLevel node);

  void Visit(TypeIdentifier node);

  void Visit(TypeReference node);

  void Visit(Value node);

  void Visit(Void node);

  void Visit(Expression node);
  void Visit(Declaration node);
  void Visit(Literal node);
  void Visit(IReference<Identifier> node);
  void Visit(Identifier node);

  public void Visit(INode node) {
    Visit((dynamic)node);
  }
}
