name: Build

on:
  push:
    branches:
      - master

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_VERSION: 7.0.x

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup C project
        uses: lukka/get-cmake@v3.25.2
        with:
          cmakeVersion: 3.24.0
          useCloudCache: ${{!env.ACT}} # Use the "cloud cache" when in the cloud.
          useLocalCache: ${{!!env.ACT}} # Use the local cache when running locally through `act`.

      - name: Build C project Unix-like
        run: |
          cd ./RadLib
          cmake -DBUILDING_DLL=1 -DCMAKE_BUILD_TYPE=Release -Bcmake-build-unix/
          cmake --build cmake-build-unix/ --target RadLib RadLibStatic
          cd ../

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Remove Windows-only projects from the sln file
        run: |
          perl -i -0pe 's/^.*? = "RadLib.*?\r?\nEndProject//gm' RadLang.sln

      - name: Build .NET project
        run: dotnet build ./RadLang.sln --configuration Release

      - name: Test .NET project
        run: dotnet test ./RadLang.sln --configuration Release
